[versions]
agp = "8.5.1"
kotlin = "2.0.0"
carApp = "1.4.0"
securityCrypto = "1.1.0-alpha06"
coroutines = "1.8.1"
preference = "1.2.1"
lifecycle = "2.8.3"
coreKtx = "1.13.1"

[libraries]
car-app = { group = "androidx.car.app", name = "app", version.ref = "carApp" }
security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "securityCrypto" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
