[env]
platform = espressif32
framework = arduino
lib_deps =
    h2zero/NimBLE-Arduino @ ^1.4.2
monitor_speed = 115200

[env:esp32c3]
board = esp32-c3-devkitm-1

[env:lolin32lite]
board = lolin32_lite

[env:esp32dev]
board = esp32dev

[env:lolin32]
board = lolin32

[env:esp32s3]
board = esp32-s3-devkitc-1

[env:nodemcu32s]
board = nodemcu-32s

[env:native]
platform = native
test_build_src = false
