[env]
platform = espressif32
framework = arduino
lib_deps =
    h2zero/NimBLE-Arduino @ ^1.4.2
monitor_speed = 115200

[env:esp32c3]
board = esp32-c3-devkitm-1
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DTRIGGER_PIN=8
    -DLED_PIN=8
    -DLED_ON_LEVEL=1

[env:esp32c3_debug]
extends = env:esp32c3
build_flags = -DCORE_DEBUG_LEVEL=4

[env:lolin32lite]
board = lolin32_lite
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DTRIGGER_PIN=26
    -DLED_PIN=22
    -DLED_ON_LEVEL=0

[env:lolin32lite_debug]
extends = env:lolin32lite
build_flags = -DCORE_DEBUG_LEVEL=4

[env:esp32dev]
board = esp32dev
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DTRIGGER_PIN=26
    -DLED_PIN=2
    -DLED_ON_LEVEL=1

[env:esp32dev_debug]
extends = env:esp32dev
build_flags = -DCORE_DEBUG_LEVEL=4

[env:lolin32]
board = lolin32
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DTRIGGER_PIN=26
    -DLED_PIN=5
    -DLED_ON_LEVEL=0

[env:lolin32_debug]
extends = env:lolin32
build_flags = -DCORE_DEBUG_LEVEL=4

[env:esp32s3]
board = esp32-s3-devkitc-1
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DTRIGGER_PIN=4

[env:esp32s3_debug]
extends = env:esp32s3
build_flags = -DCORE_DEBUG_LEVEL=4

[env:nodemcu32s]
board = nodemcu-32s
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DTRIGGER_PIN=26
    -DLED_PIN=2
    -DLED_ON_LEVEL=1

[env:nodemcu32s_debug]
extends = env:nodemcu32s
build_flags = -DCORE_DEBUG_LEVEL=4

[env:native]
platform = native
test_build_src = false
